### ISSUE TITLE
Error trying to install ppsr

### ISSUE THREAD

**Issue by mjbeggs** [paulvanderlaken/ppsr#12]
After running the commands in R Studio:
install.packages('devtools')
devtools::install_github('https://github.com/paulvanderlaken/ppsr')
 the following error message occurs:

Downloading GitHub repo paulvanderlaken/ppsr@HEAD
Error: Failed to install 'ppsr' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1

----------------------------------------------
R version 4.0.3 (2020-10-10)
R Studio Version 1.4.970
MacBook Pro 2016 running macOS Catalina 10.15.7

**Comment by mjbeggs** [comment]
The updated package ppsr_0.0.0.9100.tar.gz installed today without errors. 
Thank you.
I will now begin to use it.

**Comment by paulvanderlaken** [comment]
Great!
