### ISSUE TITLE
Plots: Hard to read numeric values inside the darker boxes...

### ISSUE THREAD

**Issue by sfd99** [paulvanderlaken/ppsr#14]
**_Paul -_** 
great pkg - thanks!

**Issue:**
Trying color yellow, 
to more easily read the black numbers in a box...
>  visualize_matrix(iris, **color = "#FFFF00"**) 

But, 
the color displayed in the plot
 is still _the same_ original default blue color,
ie: 
  the box colors do not change 
from the default blue...

My objective is to make the numeric values (colored black)
inside the darker boxes,
_more easily readable_.

Hard to read these numeric values
in the darker boxes, right now...

Help!.
**SFd99**
**latest Rstudio & R, Ubuntu Linux 20.04**
**ppsr pkg version: 0.0.0.9100**
--

**Comment by paulvanderlaken** [comment]
Found the error and fixed it in the development branch. Will try to merge it with the master this weekend. Thanks for notifying me!
