### ISSUE TITLE
Suggestion:  in correlation Fxs() make include_missings= FALSE, as default....

### ISSUE THREAD

**Issue by sfd99** [paulvanderlaken/ppsr#16]
**_Hi Paul,_**

ppsr viz plots  values  and colors are
_much more readable_ now!. 

**Easy Suggestion**:  :-)
in the **correlation** plot fxs (single and "both"),
pls make the param:
    ....  , _include_missings_ = **FALSE** _as  a default value_.

Right now,
 the default value is TRUE,
and including vars w/o correlations
takes away valuable space in the correlation plots.
(ie: Species var in iris,
 is just extra empty space...).

Thanks! / Dank U!.
**SFd99**
Rstudio/Ubuntu Linux 20.04
---

**Comment by paulvanderlaken** [comment]
It was a concious decision to default it to TRUE, as in the context of PPS you want both graphs to look similar in terns of where the scores are displayed (aligned in both matrices).
I will reconsider changing this argument to default FALSE in the next development iteration. Yet I do prefer to keep it to TRUE for `visualize_both()` at least

**Comment by sfd99** [comment]
Ok, Paul.
Understood. 
I see your reasoning, clearly.

Sincerely hope you can change to _default_ **FALSE**
in the next development version!.
It would save extra keystrokes. :-)

BUT....
maybe _the alignment_ btw _both_ plots
in  **visualize_both()**,
can still be maintained
while in default FALSE!  :-) :-) :-)

**btw, Paul:**

In the FX:
     **visualize_both()**
using explicitly the arg:
      include_missings = **FALSE** 

has no effect in the _correlations plot_, (on the right side).
It still shows "missing" var names as if  arg=TRUE.....

ie:
   ppsr::visualize_both(df = iris, include_missings = **FALSE** )

Check it out!.

Thanks! / Dank U!.
**SFd99
Rstudio/Ubuntu Linux 20.04**

**Comment by paulvanderlaken** [comment]
Thanks again for the helping me further improve this package and its defaults SFd!
I've integrated your suggestions in the development version. They will be merged in the next iteration. 
Cheers, 
Paul
