### ISSUE TITLE
devtools::check() does not work well with testing parallelized functions

### ISSUE THREAD

**Issue by paulvanderlaken** [paulvanderlaken/ppsr#19]

**Comment by paulvanderlaken** [comment]
Partially in e43b6958c635a3d2572927be7265abe843c7bb2d by putting \donttest around parallelized functions.

**Comment by paulvanderlaken** [comment]
Also in e43b6958c635a3d2572927be7265abe843c7bb2d: set all tests to use a maximum of 2 cores, in line with CRAN submission guidelines. Maybe devtools::check() does work with max 2 cores?

**Comment by glensbo** [comment]
I experience the following:
> ppsr::score_df(df = mtcars, do_parallel = TRUE, n_cores = 2)
Error in as.environment(pos) : 
  no item called "package:ppsr" on the search list

**Comment by glensbo** [comment]
I experience the following:
ppsr::score_df(df = iris, do_parallel = TRUE, n_cores = 2)
Error in as.environment(pos) : 
  no item called "package:ppsr" on the search list
In addition: There were 13 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 15 (<-localhost:11244)
2: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 14 (<-localhost:11244)
3: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 13 (<-localhost:11244)
4: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 12 (<-localhost:11244)
5: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 11 (<-localhost:11244)
6: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 10 (<-localhost:11244)
7: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 9 (<-localhost:11244)
8: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 8 (<-localhost:11244)
9: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 7 (<-localhost:11244)
10: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 6 (<-localhost:11244)
11: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 5 (<-localhost:11244)
12: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 4 (<-localhost:11244)
13: In if (isTRUE(recycle0)) .Internal(paste0(list(...), collapse,  ... :
  closing unused connection 3 (<-localhost:11244)

**Comment by paulvanderlaken** [comment]
Thanks for reporting this @glensbo.
I was able to reproduced this error on fresh R environment and will look into it with the 0.0.3 update. 
I greatly struggled making the non-exported ppsr functions available to the cluster nodes. I thought I fixed it, but apparently not : (

**Comment by glensbo** [comment]
Look forward to the update - and use all the abilities of your tool

**Comment by glensbo** [comment]
Thanks and everything seems to work

**Comment by paulvanderlaken** [comment]
That's great news!
